cuisines = [
  'American',
  'Hawaiian',
  'Indonesian',
  'North African',
  'Australian',
  'Brazilian',
  'Cajun & Creole',
  'Caribbean',
  'Chilean',
  'Chinese',
  'Cuban',
  'Danish',
  'English',
  'French',
  'German',
  'Greek',
  'Indian',
  'Irish',
  'Japanese',
  'Korean',
  'Mediterranean',
  'Mexican',
  'Jewish',
  'Middle Eastern',
  'Moroccan',
  'Portuguese',
  'Scottish',
  'Southern & Soul',
  'Southwestern',
  'Spanish',
  'Swedish',
  'Thai',
  'Turkish',
  'Vietnamese',
  'British',
  'Belgian',
  'Balinese',
  'Italian',
  'Hungarian',
  'Swiss',
  'Tunisian',
  'Asian',
  'Eastern European',
  'Dutch',
  'African',
  'Latin American',
  'Scandinavian',
  'Austrian'
].each do |name|
  Cuisine.find_or_create_by!(name: name)
end
